package com.example.workout;

import android.os.Bundle;
import android.os.CancellationSignal;
import android.widget.ImageButton;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.content.ContextCompat;

import androidx.credentials.CredentialManager;
import androidx.credentials.GetCredentialRequest;
import androidx.credentials.CredentialManagerCallback;
import androidx.credentials.GetCredentialResponse;
import androidx.credentials.exceptions.GetCredentialException;
import androidx.credentials.Credential;

import com.google.android.libraries.identity.googleid.GetGoogleIdOption;
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential;
import com.google.android.libraries.identity.googleid.GoogleIdTokenParsingException;

import Model.APIService.UserAPIService;
import Model.Repository.UserRepository;
import Model.APIService.AuthResponse;
import retrofit2.Retrofit;
import retrofit2.converter.gson.GsonConverterFactory;

public class LoginActivity extends AppCompatActivity {
    private CredentialManager credentialManager;
    private UserRepository userRepository;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.login_page);

        // 1) Initialize your repo (for example via DI or manual)
        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl("https://workout-2fa90-default-rtdb.europe-west1.firebasedatabase.app/") // The URL generated by Firebase
                .addConverterFactory(GsonConverterFactory.create())
                .build();

        UserAPIService realService = retrofit.create(UserAPIService.class);
        userRepository = new UserRepository(realService);


        // 2) Create the CredentialManager
        credentialManager = CredentialManager.create(this);

        // 3) Wire up the button
        ImageButton googleAuth = findViewById(R.id.googleRegisterButton);
        googleAuth.setOnClickListener(v -> requestGoogleIdToken());
    }

    private void requestGoogleIdToken() {
        // Build the Google ID request
        GetGoogleIdOption googleIdOption = new GetGoogleIdOption.Builder()
                // show _all_ Google accounts on the device, not just pre-authorized ones:
                .setFilterByAuthorizedAccounts(false)
                // still requires a server client ID so you get back an ID token you can verify:
                .setServerClientId(getString(R.string.server_client_id))
                // keep this false so the user always gets the choice dialog
                .setAutoSelectEnabled(false)
                .build();

        GetCredentialRequest request = new GetCredentialRequest.Builder()
                .addCredentialOption(googleIdOption)
                .build();

        // CORRECTED: only one generic parameter here
        credentialManager.getCredentialAsync(
                this,
                request,
                /* cancellationSignal= */ null,
                ContextCompat.getMainExecutor(this),
                new CredentialManagerCallback<GetCredentialResponse,GetCredentialException>() {
                    @Override
                    public void onResult(@NonNull GetCredentialResponse response) {
                        handleCredential(response.getCredential());
                    }
                    @Override
                    public void onError(@NonNull GetCredentialException e) {
                        Toast.makeText(
                                LoginActivity.this,
                                "Sign-in error: " + e.getMessage(),
                                Toast.LENGTH_LONG
                        ).show();
                    }
                }
        );
    }

    private void handleCredential(@NonNull Credential credential) {
        // 7) Check for Google ID token credential type
        if (credential instanceof GoogleIdTokenCredential) {
            GoogleIdTokenCredential gidc = (GoogleIdTokenCredential) credential;
            // 8) Parse and validate
            gidc = GoogleIdTokenCredential.createFrom(gidc.getData());
            String idToken = gidc.getIdToken();

            // 9) Send the token to your backend via repository
            new Thread(() -> {
                try {
                    AuthResponse auth = userRepository.authenticateWithGoogle(idToken);
                    runOnUiThread(() -> {
                        // TODO: store auth.getJwt(), nav to main app screen
                        Toast.makeText(this,
                                "Welcome, " + auth.getUser().getUsername(),
                                Toast.LENGTH_SHORT).show();
                    });
                } catch (Exception ex) {
                    runOnUiThread(() ->
                            Toast.makeText(this,
                                    "Auth error: " + ex.getMessage(),
                                    Toast.LENGTH_LONG).show()
                    );
                }
            }).start();

        } else {
            // not a Google ID credential
            Toast.makeText(this,
                    "Unexpected credential type: " + credential.getType(),
                    Toast.LENGTH_LONG).show();
        }
    }
}
