package com.example.workout;

import static org.junit.Assert.*;
import Model.APIService.UserAPIService;
import Model.Phone;
import Model.PhonePrefix;
import Model.Repository.UserRepository;

import org.junit.Before;
import org.junit.Test;

import Model.User;
import okio.Timeout;
import retrofit2.Call;
import retrofit2.Response;

import retrofit2.Callback;
import retrofit2.Retrofit;
import retrofit2.converter.gson.GsonConverterFactory;

import java.io.IOException;

public class UserRepositoryTest {
    private UserRepository repoReal;

    @Before
    public void setUp() {
        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl("https://workout-2fa90-default-rtdb.europe-west1.firebasedatabase.app/") // The URL generated by Firebase
                .addConverterFactory(GsonConverterFactory.create())
                .build();

        UserAPIService realService = retrofit.create(UserAPIService.class);
        repoReal = new UserRepository(realService);
    }

    @Test
    public void createUser_hitsFirebase_andReturns() {
        User newUser = new User("1","Alice","1234",new Phone(PhonePrefix.PREFIX_052, "5678111"), "a@a.com");
        User created = repoReal.createUser(newUser); // Calls the repository to create the new user in the DB
        assertNotNull(created);
        assertEquals(newUser.getUsername(), created.getUsername());
    }

}

